### PR TITLE
Handle out-of-range LAT/LON

### PR DESCRIPTION
**Pull request by pholleran**
Handle Lat/Long values reported above 90/180

### CODE REVIEW

**Comment by pholleran** [comment]
@chelm could be. I'll modify and submit the PR again.

**Comment by chelm** [comment]
@pholleran Oh we can keep this open and if you make a change to your code then just push it will sync the PR automatically.

**Comment by chelm** [comment]
(this is really awesome BTW, you are killing it!)

**Comment by pholleran** [comment]
Thanks. Do you know any reason why node dislikes the following:

```
if ((-90 <= parseFloat[locationField](feature.latitude) <= 90) &&...)
```
But is okay if it is broken out into two separate statements? I can't seem to get it to evaluate.

**Comment by chelm** [comment]
yeah JS wont like those types of inequalities. 

you need to be explicit

```javascript 
var lat = parseFloat[locationField](feature.latitude);
var lng = parseFloat[locationField](feature.longitude);
if ((lat < -90 || lat > 90) || (lng < -180 || lng > 180)){
  // invalid geom
}

```

**Comment by pholleran** [comment]
Just pushed a change. Once we get this and the cache auto-dump thing figured out Detroit should be rocking and rolling.

Thanks for all your help.

**Pull request merged**
